### ISSUE TITLE
Net::IPv4Addr

### ISSUE THREAD

**Issue by benkasminbullock** [autarch/blog.urth.org#4]
Did you try Net::IPv4Addr for your blog post?

This has about twenty dependent modules, many of them via Net::IPv6Addr.

**Comment by autarch** [comment]
I will take a look. If it has issues I will reach out to the maintainer before updating my blog post.

**Comment by autarch** [comment]
Yeesh, last release was in 2000. So if there are bugs then the author is probably not available.

**Comment by benkasminbullock** [comment]
If it has the bug then I can change Net::IPv6Addr though, which is where all the dependencies are.

**Comment by autarch** [comment]
I can confirm that it is affected by this issue. I wanted to give the author some time to respond, but the email I sent to them bounced.

**Comment by benkasminbullock** [comment]
On Wed, 31 Mar 2021 at 10:06, Dave Rolsky ***@***.***> wrote:

> I can confirm that it is affected by this issue. I wanted to give the
> author some time to respond, but the email I sent to them bounced.
>

I've removed the dependence on this module in Net::IPv6Addr. It was
actually only using the Net::IPv4Addr to validate ipv4 parts of ipv6
addresses.

>

**Comment by benkasminbullock** [comment]
Thanks. Regarding the dependencies, I just removed it since it was only being used for validation.

https://metacpan.org/release/BKB/Net-IPv6Addr-1.02
